### PR TITLE
Nsfw filtering

### PR DESCRIPTION
**Pull request by sverzegnassi**

### CODE REVIEW

**Comment by sverzegnassi** [comment]
NOTE - I had to change the way our backend currently works, since it was designed for caching all the remote data within a single session.
By activating the NSFW toggle, app cache gets cleaned, and models are reset. It seems to work okay, however I'd prefer to get a second pair of eyes on this :D

**Comment by bhdouglass** [comment]
@sverzegnassi this looks awesome, except if I go to turn off the "hide nsfw" checkbox and hit cancel on the popup it appears to be off. But leaving and returning to the settings page will show that it's actually still on.

**Comment by sverzegnassi** [comment]
Ok, fixed. The abortion signal didn't get disconnected when the dialog was closed. That caused 'checked = !checked' to be set twice. Now should be okay.

**Comment by bhdouglass** [comment]
LGTM

**Pull request merged**
