### PR TITLE
Handle offline status

### PR DESCRIPTION
**Pull request by sverzegnassi**

### CODE REVIEW

**Comment by sverzegnassi** [comment]
To be merged after #15

**Comment by bhdouglass** [comment]
@sverzegnassi this is weird: I started the app offline, saw the offline state, turned on wifi, everything loaded fine. BUT when I go into an app it looks like it's trying to download/install the app (but it's not actually doing that).

**Comment by bhdouglass** [comment]
But the offline state works well!

**Comment by sverzegnassi** [comment]
Ok, will have a look at it. Might need a bit of work.

**Pull request closed without merging**
