### PR TITLE
show "Downgrade" instead of "Upgrade" when versionString < installedVersionString

### PR DESCRIPTION
**Pull request by PeterNerlich**
[#164](https://github.com/UbuntuOpenStore/openstore-meta/issues/164)

### CODE REVIEW

**Comment by bhdouglass** [comment]
Thanks for the contribution! Unfortunately just checking the version string isn't enough as we use revisions to check for updates. I believe in this case, when the apps is from outside the OpenStore, the revision of the installed app will be 0.

**Comment by bhdouglass** [comment]
Also, can you leave out the updates to the po files? I should probably fix that to be relative

**Comment by PeterNerlich** [comment]
Ha, I didn't expect this to go through being so easy, so no worries :3
Still, I think there should be an easier way to check whether to show upgrade or downgrade. Maybe it's already enough comparing the revision numbers for that and just show something like "replace" for those with 0 or only use the version string in this case? Anyway, I regard this as important, since it seems to me that quite some people already fell for that, mistaking it for a genuine upgrade.

**Comment by bhdouglass** [comment]
It probably makes sense to show the button as "replace" or something and also have a warning as to _why_ we want to replace it.

**Comment by bhdouglass** [comment]
I'm going to close this since its very old and doesn't follow the update checking that we currently have in place. Feel free to open another pull request if changes are made to use revisions rather than version numbers.

**Pull request closed without merging**
